#!/bin/bash
#------------------------------------------------------------------------------
# BUILD_BASE doesn't replace the SATELLITE_RELEASE, need both
#------------------------------------------------------------------------------
base=$MUSE_WORK_DIR

# echo ePlus2024::build_config_muse:000: MUSE_VERBOSE:.$MUSE_VERBOSE.

if [ ".$MUSE_VERBOSE" != ".0" ] ; then echo ePlus2024::build_config_muse:001: $\0:$0 : \$PWD=$PWD  \$base=$base ; fi

# pkg=`pwd | awk -F / '{print $(NF-1)}'`
pkg=`echo $0 | awk -F / '{print $(NF-2)}'`

        pkg_dir=$MUSE_WORK_DIR/$pkg
pkg_include_dir=$base/include/$pkg

# echo ePlus2024::build_config_muse: package=$pkg

list_of_subpackages="ana"
#------------------------------------------------------------------------------
# package and its subpackages
#------------------------------------------------------------------------------
if [ ! -d $pkg_include_dir ] ; then
    if [ $MUSE_VERBOSE != 0 ] ; then echo ePlus2024::build_config_muse: pwd=$pwd ; creating $base/include/$pkg ; fi
    mkdir -p $pkg_include_dir
fi
#------------------------------------------------------------------------------
# make symbolic links local, as they are 
#------------------------------------------------------------------------------
for d in $list_of_subpackages ; do
    if [[ -e $base/include/$pkg ]] && [[ ! -e $base/include/$pkg/$d ]] ; then 
	cmd="ln -s ../../$pkg/$d/$d $pkg_include_dir/$d"
	if [ $MUSE_VERBOSE != 0 ] ; then echo `pwd`$0 : executing: $cmd ; fi
	$cmd
    fi
done
